### ISSUE TITLE
Question: What is Explore Average Reward

### ISSUE THREAD

**Issue by notsql** [AI4Finance-Foundation/ElegantRL#111]
Hi, don't quite understand what explore average reward is on the charts produced.

Thank you

**Comment by XiaoYangLiu-FinRL** [comment]
The average reward value during the training process.

**Comment by notsql** [comment]
![image](https://user-images.githubusercontent.com/77440908/153692922-547c1298-df69-4ef2-9f2d-7371e42d870b.png)

Just to be sure, in this table, `expR` is "Explore Average Reward"? If yes, what is the difference between average reward value and `avgR`. Thank you.

**Comment by hmomin** [comment]
So, I hope I can clarify this a bit.

When training an agent with ElegantRL, there are two main "phases" you can be in: **training** the agent or **evaluating** the agent.

On each step of training the agent, a `(state, action, reward, next_state)` tuple is stored in the replay buffer.<sup>[1](#footnote1)</sup> Additionally, the `reward` here is thought of as an *exploring* reward, relatively small on each individual step, but it's the incremental reward gained from traversing through the environment with whatever policy the agent happens to be using at that time.

`expR` is the average reward gained on each individual step during the training process.

On the other hand, after training for *M* steps, we like to evaluate the agent's current policy to see how well it's doing. To evaluate the agent, it takes *N* complete traversals through the environment.<sup>[2](#footnote2)</sup>

`avgR` is the average return achieved for these *N* traversals during evaluation time, **not** training time. While these *N* traversals are happening, the agent's policy isn't changing, because it's not *training*, it's *evaluating*. This gives us a more robust measure for how "good" the agent's current policy is.

As an example, here is a learning curve plot I generated for the `Ant-v3` environment training with PPO:

![plot_learning_curve](https://user-images.githubusercontent.com/72412509/155177187-06695713-bc31-4a43-97f7-e7e1fbd676d9.jpg)

Notice how "Explore Avg Reward" is scaled on the right in green and "Episode Return" is scaled on the left. The red line is measuring `avgR`, the average return achieved for some number of traversals during evaluation time. As expected, if your agent is learning properly, it should be going up(-ish) over time.

The green line is measuring `expR` over time, the average reward received on each individual step during training time or "exploring" time. It's usually a good sign if this is also going up over time, because it indicates that your agent is collecting larger and larger rewards on each step during the training process (on average, at least).

If this is a satisfactory answer, please be sure to close the issue.

<br/>
<br/>

<a name="footnote1">1</a>: It's not quite `(state, action, reward, next_state)`, but this is good enough for what I'm trying to explain. The key is the `reward` part.

<a name="footnote2">2</a>: *N* is called `eval_times` in the code.
