### ISSUE TITLE
Some code questions

### ISSUE THREAD

**Issue by ghaffari903** [AI4Finance-Foundation/ElegantRL#112]
Again, thanks for your implementations, I study codes, I have some questions, thanks someone for writing the answer.

1-What is the use of reward scaling?
2- In Step function[https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/finrl_meta/env_stock_trading/env_stock_trading.py](https://github.com/AI4Finance-Foundation/FinRL/issues/url) :
min_stock_rate and min_action whats for? in trading we see qty < min_action, I did not understand what it is used for?

3- I printed real actions in this code, its count is 0 most of time, but reward is applied to amount!!!!
if self.turbulence_bool[self.day] == 0:
min_action = int(self.max_stock * self.min_stock_rate) # stock_cd
for index in np.where(actions < -min_action)[0]: # sell_index:
if price[index] > 0: # Sell only if current asset is > 0
sell_num_shares = min(self.stocks[index], -actions[index])
self.stocks[index] -= sell_num_shares
self.amount += (
price[index] * sell_num_shares * (1 - self.sell_cost_pct)
)
self.stocks_cool_down[index] = 0
for index in np.where(actions > min_action)[0]: # buy_index:
if (
price[index] > 0
): # Buy only if the price is > 0 (no missing data in this particular date)
buy_num_shares = min(self.amount // price[index], actions[index])
self.stocks[index] += buy_num_shares
self.amount -= (
price[index] * buy_num_shares * (1 + self.buy_cost_pct)
)
self.stocks_cool_down[index] = 0`

**Comment by Burntt** [comment]
Hello Ghaffari,

1. Reward scaling determines how big your actions become. For example if you only have 2k cash in the start and your reward scaling is still high the trades will exceed your balance at all times. Just scale it up or down accordingly.

2. min_action is the minimum amount to be traded. Many exchanges have a limitation on the minimum amount and this should be accordingly adjusted to the exchange you are trading on. min_stock_rate I do not know about.

3. I'm sorry, I fail to understand your problem here. Maybe elaborate a bit more specified?

Hope it helps! ~ Berend

**Comment by ghaffari903** [comment]
Dear @Burntt 
thank you, Mr. Astarag https://github.com/AI4Finance-Foundation/FinRL/issues/465 explained to me.
